# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: !secret microshift_ip

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  country: !secret country
  #unit_System: metric

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret homne_network_cidr
        - fd00::/8
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant

lovelace:
  mode: yaml
  resources:
    - url: /local/auto-entities.js
      type: module

mqtt:
  sensor:
  - name: "Bezug 1.8.0"
    state_topic: "vzlogger/data/chn0/agg"
    state_class: total_increasing
    unit_of_measurement: Wh
    device_class: energy
  - name: "Einspeisung 2.8.0"
    state_topic: "vzlogger/data/chn1/agg"
    state_class: total_increasing
    unit_of_measurement: Wh
    device_class: energy
  - name: "Erzeugung 1.8.0"
    state_topic: "vzlogger/data/chn2/agg"
    state_class: total_increasing
    unit_of_measurement: Wh
    device_class: energy
#  - name: "Gas Impulse" # configured below
#    state_topic: "vzlogger/data/chn3/agg"
#    state_class: total
  - name: "Warmwasser Speicher Rücklauf"
    state_topic: "vzlogger/data/chn4/raw"
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
  - name: "Warmwasser Speicher Vorlauf"
    state_topic: "vzlogger/data/chn5/raw"
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"


wake_on_lan: 

sensor:

###### BEGIN GASZAEHLER #####
counter:
  gas_impulse_agg:
    initial: 0
    step: 1
    name: Gas Impulse aggregiert

automation gaszaehler:
- alias: Gas Impulse aggregieren
  description: ""
  trigger:
    - platform: mqtt
      topic: vzlogger/data/chn3/agg
  condition: []
  action:
    - service: counter.set_value
      data:
        value: >-
          {{ states('counter.gas_impulse_agg')|int + trigger.payload|int }}
      target:
        entity_id: counter.gas_impulse_agg
  mode: single

template:
  - sensor: 
    - name: "Gaszähler m³"
      unique_id: gaszaehler
      state: "{{ states ('counter.gas_impulse_agg') | float * 0.01 }}"
      unit_of_measurement: "m³"
      icon: "mdi:fire"
      device_class: gas
      state_class: total_increasing
  # - sensor: 
  #   - name: "Gaszähler kWh"
  #     unique_id: gaszaehler_kwh
  #     state: "{{ (states ('sensor.gaszaehler') | float * 0.9178 * 11.3740) | round(3) }}"
  #     unit_of_measurement: "kWh"
  #     icon: "mdi:fire"
  #     device_class: gas
  #     state_class: total_increasing

####### END GASZAEHLER #######

device_tracker:
  - platform: bluetooth_le_tracker
#    track_new_devices: True


notify:
  - name: signal
    platform: signal_messenger
    url: !secret signal_rest_api_url # the URL where the Signal Messenger REST API is listening
    number: !secret telefone_number # the sender number
    recipients: # one or more recipients
      - !secret signal_group 


# logger:
#   default: info
#   logs:
#     libdyson: debug
#     custom_components.dyson_local: debug
#     custom_components.dyson_cloud: debug
#     custom_components.truenas: debug