# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome

microshift_ip: 192.168.1.2
homne_network_cidr: 192.168.178.1/24

latitude: 50.450001
longitude: 30.523333
elevation: 179

# see https://github.com/mampfes/hacs_waste_collection_schedule
waste_collection_key: changeme
waste_collection_kommune: changeme
waste_collection_bezirk: changeme
waste_collection_strasse: changeme
waste_collection_strasse_hnr: changeme


# see https://support.getawair.com/hc/en-us/articles/360049221014-Awair-Element-Local-API-Feature
awair_local_api_url: http://awair_hostname_or_ip/air-data/latest

telefone_number: "+4911111111"
signal_group: "group.abcdefg"
signal_rest_api_url: "http://some_dns_name"

school_calendar_url: https://changeme