apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: volkszaehler

resources:
#- vzlogger.configmap.yaml
- vzlogger.deployment.yaml
- vzlogger.service.yaml
- vzlogger.route.yaml

configMapGenerator:
- name: vzlogger
  files: 
  - vzlogger.conf

images:
- name: vzlogger
  newName: localhost/vzlogger

