apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mosquitto.serviceaccount.yaml
- mosquitto.deployment.yaml
- mosquitto.service.yaml
- mosquitto.route.yaml
- mosquitto.route2.yaml
- anyuid.rolebinding.yaml
- scc-anyuid.role.yaml

images:
- name: mosquitto
  newName: eclipse-mosquitto
  newTag: "2.0"

configMapGenerator:
- name: mosquitto
  files:
  - mosquitto.conf