apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mosquitto.deployment.yaml
- mosquitto.service.yaml

images:
- name: mosquitto
  newName: eclipse-mosquitto
  newTag: 2.0.12