apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30100
    - name: wss
      port: 9001
      targetPort: 9001
      nodePort: 30101
  selector:
    app: mosquitto
  type: NodePort # NodePort to allow "hostNetwork: true" containers to access the service