### THIS IS NOT USED AT THE MOMENT ###


FROM ghcr.io/home-assistant/home-assistant:stable
#icalendar/icalevents for waste_collection_schedule
#RUN pip3 install calendar==4.0.9 icalevents==0.1.25 libdyson==0.8.11
#RUN pip3 install libdyson==0.8.11
