apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- homeassistant.deployment.yaml
- homeassistant.pvc.yaml
- homeassistant.service.yaml
- homeassistant.route.yaml

configMapGenerator:
- name: homeassistant
  files: 
  - config/configuration.yaml
  - config/scenes.yaml
  - config/scripts.yaml
  - config/secrets.yaml
  - config/automations.yaml

images:
- name: homeassistant
#  newName: ghcr.io/home-assistant/home-assistant
#  newTag: stable
  newName: localhost/home-assistant
  newTag: latest

