apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- homeassistant.deployment.yaml
- homeassistant.pvc.yaml
- homeassistant.service.yaml
- homeassistant.route.yaml
- signalapi.deployment.yaml
- signalapi.pvc.yaml
- signalapi.service.yaml
- signalapi.route.yaml

configMapGenerator:
- name: homeassistant
  files: 
  - config/configuration.yaml
  - config/secrets.yaml

images:
- name: homeassistant
  newName: ghcr.io/home-assistant/home-assistant
  newTag: stable
#  newName: localhost/home-assistant
#  newTag: latest
- name: signal-cli-rest-api
  newName: docker.io/bbernhard/signal-cli-rest-api
  newTag: latest