apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: volkszaehler

resources:
- database.configmap.yaml
- database.deployment.yaml
- database.pvc.yaml
- database.service.yaml
- pushserver.deployment.yaml
- pushserver.route.yaml
- pushserver.service.yaml
#- volkszaehler.configmap.yaml
- volkszaehler.deployment.yaml
- volkszaehler.route.yaml
- volkszaehler.service.yaml

configMapGenerator:
- name: volkszaehler
  files:
  - config.yaml

images:
- name: volkszaehler
  #newName: localhost/volkszaehler
  newName: quay.io/wrichter/volkszaehler
