apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: volkszaehler

resources:
- cronjob.yaml

configMapGenerator:
- name: cputemp
  files:
  - cputemp.ini

images:
- name: cputemp
  newName: localhost/cputemp

