apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-red.deployment.yaml
- node-red.pvc.yaml
- node-red.service.yaml
- node-red.route.yaml

images:
- name: node-red
  newName: quay.io/wrichter/node-red
  newTag: latest

