apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- homebridge.deployment.yaml
- homebridge.pvc.yaml
- homebridgeUI.service.yaml
- homebridgeUI.route.yaml


images:
- name: homebridge
  newName: oznu/homebridge

