apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: volkszaehler

resources:
- cronjob.yaml

configMapGenerator:
- name: weather
  files:
  - weather.ini

images:
- name: weather
  newName: localhost/weather

