apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- esphome.deployment.yaml
- esphome.pvc.yaml
- esphome.service.yaml
- esphome.route.yaml
- esphome.serviceaccount.yaml
- scc-hostnetwork.yaml
- hostnetwork.rolebinding.yaml


images:
- name: esphome
  newName: ghcr.io/esphome/esphome
  newTag: stable

