apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-hostnetwork
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostnetwork
  resources:
  - securitycontextconstraints
  verbs:
  - use