homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto.mqtt
serial:
  port: /dev/ttyACM0
  adapter: zstack
frontend:
  enabled: true
  port: 8080
advanced:
  last_seen: ISO_8601_local
  network_key: '!secret network_key'
  pan_id: 6755
  ext_pan_id:
    - 221
    - 170
    - 221
    - 170
    - 221
    - 170
    - 221
    - 170
  log_level: warning
  log_output:
    - console
device_options: {}
availability:
  enabled: false
devices: devices.yaml
groups: groups.yaml
version: 4