apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: zigbee2mqtt

resources:
- zigbee2mqtt.deployment.yaml
- zigbee2mqtt.route.yaml
- zigbee2mqtt.service.yaml
- zigbee2mqtt.pvc.yaml


configMapGenerator:
- name: zigbee2mqtt
  files:
  - configuration.yaml

secretGenerator:
- name: zigbee-network-key
  files: 
  - secret.yaml

images:
- name: zigbee2mqtt
  newName: ghcr.io/koenkk/zigbee2mqtt
  newTag: "2"